spring.application.name=bff-service
server.port=8080

producto-service.url=http://localhost:8081
usuario-service.url=http://localhost:8082
pedido-service.url=http://localhost:8083
spring.security.oauth2.resourceserver.jwt.issuer-uri=