spring.application.name=bff-service
server.port=8080

producto-service.url=http://10.0.133.181:8081
usuario-service.url=http://10.0.133.181:8082
pedido-service.url=http://10.0.133.181:8083

spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER}
spring.security.oauth2.resourceserver.jwt.audiences=${API_AUDIENCE}
logging.level.org.springframework.security=DEBUG