spring.application.name=bff-service
server.port=8080

producto-service.url=http://localhost:8081
usuario-service.url=http://localhost:8082
pedido-service.url=http://localhost:8083
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_F7SREFccO

spring.security.oauth2.resourceserver.jwt.audiences=https://api.peluchin.local